# Generated by Django 3.0.8 on 2020-08-07 16:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputModelForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名前')),
                ('age', models.IntegerField(default=0, verbose_name='年齢')),
                ('mail', models.EmailField(max_length=255, verbose_name='メールアドレス')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('history', models.CharField(max_length=255, verbose_name='背景')),
                ('done', models.CharField(max_length=255, verbose_name='実績')),
                ('question', models.CharField(max_length=255, verbose_name='問いかけ')),
                ('idea', models.CharField(max_length=255, verbose_name='考え')),
                ('reference', models.CharField(max_length=255, verbose_name='参考文献')),
                ('created_at', models.DateField(default=django.utils.timezone.now, verbose_name='作成日')),
            ],
        ),
    ]
