# Generated by Django 3.0.8 on 2020-08-07 21:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_inputmodelform_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputmodelform',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='作成日'),
        ),
    ]
